# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TangoSampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Tango', '~> 1.0.1'
  # Pods for TangoSampleApp

end

target 'TangoSampleAppNotificationExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'TangoRichNotification', '~> 1.0.0'
  # Pods for TangoSampleAppNotificationExtension

end
